#!/bin/bash
# PRAGRAM NAME: xxxx
#

## Gathering IP Address.
IPADD=""

function askIPADD {
IPADD=$(hostname -I)
}

askIPADD

until [[ $IPADD != "" ]]; do
   askIPADD
   sleep 6
done

## Gathering Gateway Address.
GATEWAY=""

function askGATEWAY {
GATEWAY=$(ip r | grep default | cut -f 3- -d ' ' | cut -f 1 -d ' ')
}

askGATEWAY

until [[ $GATEWAY != "" ]]; do
   askGATEWAY
   sleep 6
done

## Gathering Time Stamp.
DATE=$(date)


## Present information.
echo "Datalogger ON (IP: $IPADD | GW: $GATEWAY) --> $DATE"
