#!/bin/bash
# PRAGRAM NAME: xxxx
#

sleep 10

while :
do
   IPADD=""

   function askIPADD {
   IPADD=$(hostname -I)
   }

   askIPADD

   until [[ $IPADD != "" ]]; do
      DATE=$(date)
      echo "Datalogger is not connected --> $DATE" >> ~/app-pingmon/log-conn.txt
      sleep 6
      askIPADD
   done

   sleep 6
done
