#!/bin/bash
# PRAGRAM NAME: xxxx
#

IPADD=""

function askIPADD {
IPADD=$(hostname -I)
}

askIPADD

if [[ $IPADD == "" ]]
then
   DATE=$(date)
   echo "Datalogger is not connected --> $DATE" >> ~/app-pingmon/log-conn.txt
fi
